# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.064}, 
    {id: 1, size: 0.064}, 
    {id: 2, size: 0.064}, 
    {id: 3, size: 0.064}, 
    {id: 4, size: 0.036599},
    {id: 8, size: 0.062836},
    {id: 12, size: 0.062836},
    {id: 18, size: 0.037425},
    {id: 20, size: 0.042285},
    {id: 28, size: 0.062836},
    {id: 21, size: 0.062836},
    {id: 48, size: 0.062836},
    {id: 82, size: 0.062836}
  ]

# standalone_tags:
#   [
#     {id: 0, size: 0.1277},
#     {id: 1, size: 0.1277},
#     {id: 2, size: 0.1277},
#     {id: 3, size: 0.1277}
#   ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

tag_bundles:
  [
    {
      name: 'Robot',
      layout:
        [
          {id: 0, size: 0.064, x: -0.04,  y: 0.06175,   z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.064, x: 0.04,   y: 0.06175,   z: 0.0},
          {id: 2, size: 0.064, x: -0.04,  y: -0.06175,  z: 0.0},
          {id: 3, size: 0.064, x: 0.04,   y: -0.06175,  z: 0.0}
        ]
    }
  ]